version: '3'

services:
  api:
    build: .
    container_name: sms-api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker_whatsapp:
    build: .
    command: celery -A app.celery_worker.celery worker -Q whatsapp_queue --loglevel=info
    depends_on:
      - rabbitmq

  worker_telegram:
    build: .
    environment:
      - TELEGRAM_GATEWAY_TOKEN={TOKEN from https://gateway.telegram.org/account/api}
    command: celery -A app.celery_worker.celery worker -Q telegram_queue --loglevel=info
    depends_on:
      - rabbitmq

  worker_sms:
    build: .
    command: celery -A app.celery_worker.celery worker -Q sms_queue --loglevel=info
    depends_on:
      - rabbitmq
